# Greeting config
# Everything here is js simple text n color codes (the & symbol)
# Add or change wtv u want. {player} gets replaced with whoever
# joined or left. One phrase from each list is picked at random every time,
# so it won't feel repetitive. Restart da server (or /reload confirm)
# after changing.

join-border: "&d✦•--┈๑⋅⋯ &f✿ &d⋯⋅๑┈--•✦"
join-face: "(>⩊<)"
join-phrases:
  - "&f{player} &7came bc they finished brainrotting"
  - "&f{player} &7barged into the room"
  - "&f{player} &7came out of their mother's basement"
  - "&f{player} &7arrived to touch grass"
  - "&f{player} &7forgot to shower"

leave-border: "&d✦•--┈๑⋅⋯ &f✿ &d⋯⋅๑┈--•✦"
leave-face: "(ᗜ⩊ᗜ)"
leave-phrases:
  - "&f{player} &7went to find their vape"
  - "&f{player} &7gone to have a smoke break"
  - "&f{player} &7went to get milk"
  - "&f{player} &7is finally going to shower"
  - "&f{player} &7lost all their aura"
